schema_version = "1.0.0"

id = "Miku_Green"
version = "1.0.0"
name = "Miku Green"
tagline = "A Miku theme for Blender"
maintainer = "NomoTen"

type = "theme"
tags = ["Light"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-2.0-or-later",
]