github.com:
    users:
        Parad1gmSh1ft72:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Parad1gmSh1ft72
