# load profiles from /etc/profile.d
#  (to disable a profile, just remove execute permission on it)
for profile in /etc/profile.d/*.sh; do
  if [ -x $profile ]; then
    . $profile
  fi
done
unset profile

# End of file
