schema_version = "1.0.0"
id = "BDPT"
version = "1.0.0"
name = "Blender Dark Plus Theme"
tagline = "Make blender look Saturated while making stuff easier too see"
maintainer = "Koyoinu"
type = "theme"
tags = ["High Contrast", "Dark"]
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-2.0-or-later",
]